name: Tests

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }} tests

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov
          tools: cs2pr

      - name: Install dependencies
        run: |
          composer install --no-interaction

      - name: Run phplint - Syntax check
        run: ./vendor/bin/phplint -c  ci/phplint.yml src
      - name: Run phpcs - PSR2 check
        run: ./vendor/bin/phpcs --standard=ci/phpbcs.xml src
